Repository bomlang/FESP01-Final-Project, pull requests merged in 2023-11, with the labels that each got.

#9 [Desing] 헤더 레이아웃 디자인작업 완료
  .github/pull_request_template.md
  .gitmessage.txt
  package-lock.json
  package.json
  public/youtubeLogo.svg
  src/App.test.tsx
  src/App.tsx
  src/components/SearchBar.tsx
  src/layout/header.tsx
  tsconfig.json
Labels: HTML / CSS

#11 Feat video component
  src/App.tsx
  src/assets/480x270.svg
  src/components/VideoComponets.tsx
  src/layout/VideoDetail.tsx
  src/layout/VideoMain.tsx
  tailwind.config.js
Labels: HTML / CSS, React

#12 유튜브 목록, 상세 페이지 데이터 가져왔습니다.
  package-lock.json
  package.json
  src/App.tsx
  src/data.d.ts
  src/layout/Header.tsx
  src/layout/RootLayout/RootLayout.tsx
  src/pages/GetData.tsx
  src/pages/GetDetailData.tsx
  src/pages/NotFound.tsx
  src/pages/VideoDetail.tsx
  src/pages/VideoMain.tsx
Labels: Feature, React, API

#14 [Chore, Design] 헤더 레이아웃 반응형 디자인 구현 & carco를 사용하여 절대경로 지정
  craco.config.js
  package-lock.json
  package.json
  src/App.tsx
  src/components/SearchBar.tsx
  src/components/VideoComponets.tsx
  src/layout/Header.tsx
  src/pages/VideoDetail.tsx
  src/pages/VideoMain.tsx
  tailwind.config.js
  tsconfig.extend.json
  tsconfig.json
Labels: HTML / CSS, Setting

#15 [Merge] develop 브랜치 병합 및 경로 일부 변경
  .prettierrc
  src/App.tsx
  src/components/VideoComponets.tsx
  src/data.d.ts
  src/pages/VideoMain.tsx
  tailwind.config.js
Labels: HTML / CSS, React

#17 메인 페이지 크기에 따른 이미지 가져오기와 뒤로가기 버튼 만들었습니다.
  public/goBack.svg
  src/components/BackButton.tsx
  src/components/VideoComponets.tsx
  src/data.d.ts
  src/layout/Header.tsx
  src/utils/getData.ts
  src/utils/getImage.ts
  tsconfig.extend.json
Labels: Feature

#18 videoMain, videoDetail 페이지에 데이터 렌더링 되도록 함
  src/App.tsx
  src/components/VideoComponets.tsx
  src/data.d.ts
  src/layout/Header.tsx
  src/pages/GetDetailData.tsx
  src/pages/VideoDetail.tsx
  src/pages/VideoMain.tsx
  src/utils/getData.ts
  src/utils/getImage.ts
Labels: Feature

#23 videoDetail 페이지 레이아웃
  src/pages/VideoDetail.tsx
Labels: HTML / CSS

#24 [Design] 반응형 breakpoint 수정 및 반응형 깨짐 이슈 수정 진행중
  src/components/VideoComponets.tsx
  src/pages/VideoDetail.tsx
  src/pages/VideoMain.tsx
  tailwind.config.js
Labels: Bug, HTML / CSS, Feature, Fix, React

#26 videoDetail 페이지 관련된 영상 레이아웃 수정
  src/components/RelatedVideo.tsx
  src/components/VideoDetailItem.tsx
  src/data.d.ts
  src/pages/GetData.tsx
  src/pages/GetDetailData.tsx
  src/pages/VideoDetail.tsx
  src/utils/getData.ts
  src/utils/getImage.ts
Labels: Docs, HTML / CSS, React

#27 댓글 추가, 댓글 컴포넌트 디자인 완성
  public/smile.jpeg
  public/smile.png
  src/components/AddComment.tsx
  src/components/Button.tsx
  src/components/Comment.tsx
  src/components/RelatedVideo.tsx
  src/pages/VideoDetail.tsx
Labels: HTML / CSS

#28 댓글 컴포넌트 만들었습니다.
  src/components/AddComment.tsx
  src/components/Button.tsx
  src/components/Comment.tsx
  src/pages/VideoDetail.tsx
Labels: HTML / CSS, Feature, React

#29 [Feat | Design | Merge] 더보기 토글 기능 구현 및 반응형 수정, develop Merge
  src/components/VideoComponets.tsx
  src/components/VideoDetailItem.tsx
  src/layout/Header.tsx
  src/pages/VideoMain.tsx
  tailwind.config.js
Labels: HTML / CSS, Feature, Fix, React

#30 [Feat, Fix] 검색창 기능구현 및 검색바 lgpc버전 크기 추가
  .env
  .prettierrc
  package-lock.json
  package.json
  src/api/commentApi.ts
  src/api/formatDateDifference.ts
  src/components/RelatedVideo.tsx
  src/components/SearchBar.tsx
  src/components/VideoComponets.tsx
  src/hooks/SearchVideo.ts
  src/index.tsx
  src/layout/Header.tsx
  src/layout/RootLayout/RootLayout.tsx
  src/pages/VideoDetail.tsx
  src/pages/VideoMain.tsx
  src/store/searchBarValueAtom.ts
  src/store/videoAtom.ts
  src/utils/getData.ts
  tsconfig.extend.json
Labels: HTML / CSS, Feature, Fix, Refactor

#33 상세페이지 댓글 디자인, 반응형에 따른 관련 영상 위치 조정
  src/components/AddComment.tsx
  src/components/Button.tsx
  src/components/Comment.tsx
  src/components/RelatedVideo.tsx
  src/components/VideoDetailItem.tsx
  src/pages/VideoDetail.tsx
  src/utils/focusContentEditableTextToend.ts
Labels: HTML / CSS, Feature, React

#34 [Feat] Supabase를 이용한 댓글 등록기능 및 삭제기능 함수 등록
  src/api/commentApi.ts
  src/components/AddComment.tsx
  src/components/Comment.tsx
  src/interface.ts
  src/pages/VideoDetail.tsx
  src/pages/VideoMain.tsx
Labels: Feature

#35 댓글 데이터 가져오기
  package-lock.json
  package.json
  src/api/commentApi.ts
  src/assets/480x270.svg
  src/components/Comment.tsx
  src/components/VideoComponets.tsx
  src/interface.ts
  src/pages/VideoDetail.tsx
  src/utils/focusContentEditableTextToend.ts
  src/utils/getData.ts
Labels: Feature, React, API

#39 댓글 추가, 삭제 후 리렌더링 되도록 함
  src/api/commentApi.ts
  src/components/AddComment.tsx
  src/components/Comment.tsx
  src/interface.ts
  src/pages/VideoDetail.tsx
Labels: Feature, React, API

#41 [Refactor | Merge] 반응형 렌더링 조건식 함수 사용 및 코드 리팩토링
  src/components/RelatedVideo.tsx
  src/pages/VideoDetail.tsx
Labels: Bug, Fix, React, Refactor

#43 해당 영상에 따른 댓글만 불러오기
  src/api/commentApi.ts
  src/components/AddComment.tsx
  src/components/Comment.tsx
  src/interface.ts
  src/pages/VideoDetail.tsx
Labels: Feature, React, API

#44 [Feat] Youtube API 연결 및 데이터 통신
  src/api/getVideoAPI.ts
  src/components/VideoComponets.tsx
  src/pages/VideoMain.tsx
Labels: React, API

#45 [Feat, Fix] 댓글 수정기능 추가
  .gitignore
  src/api/commentApi.ts
  src/components/AddComment.tsx
  src/components/Comment.tsx
  src/components/SearchBar.tsx
  src/components/VideoDetailItem.tsx
  src/pages/VideoDetail.tsx
  src/store/commentAtom.ts
Labels: Docs, Feature, Fix, API

#46 [Feat] 댓글 스크롤시 로딩기능 & 메인페이지 무한스크롤 기능 구현
  .env
  package-lock.json
  package.json
  src/api/commentApi.ts
  src/api/getVideoAPI.ts
  src/components/AddComment.tsx
  src/components/Comment.tsx
  src/components/VideoComponets.tsx
  src/components/YoutubeVideo.tsx
  src/interface.ts
  src/pages/VideoDetail.tsx
  src/pages/VideoMain.tsx
Labels: Feature, Fix, API

#47 [Feat] 채널 썸네일 렌더링 및 영상 썸네일 비율 설정
  .env
  src/api/commentApi.ts
  src/components/VideoComponets.tsx
  src/components/VideoDetailItem.tsx
  src/pages/VideoDetail.tsx
  src/store/channelThumbnailAtom.ts
Labels: Fix, React, API

#48 관련 동영상 무한 스크롤 기능
  src/api/getRelatedVideo.ts
  src/components/VideoComponets.tsx
  src/components/VideoDetailItem.tsx
  src/pages/VideoDetail.tsx
  src/pages/VideoMain.tsx
Labels: Feature, React, API

#49 [Feat]영상 렌더링 및 재생 / Hover시 하나만 재생될 수 있도록 조건처리 진행중
  public/index.html
  src/api/getVideoAPI.ts
  src/components/SearchBar.tsx
  src/components/VideoComponets.tsx
  src/components/VideoDetailItem.tsx
  src/index.css
  src/layout/Header.tsx
  src/pages/VideoDetail.tsx
  src/pages/VideoMain.tsx
  src/store/channelThumbnailAtom.ts
  src/store/videoHoveringAtom.ts
  src/tailwind.css
  tailwind.config.js
Labels: Feature, React, API

#51 [Fix] VideoMain에서 hover 시 다중 영상 재생 수정 진행중
  src/components/VideoComponets.tsx
  src/pages/VideoDetail.tsx
  src/pages/VideoMain.tsx
  src/store/videoHoveringAtom.ts
Labels: Bug, Fix, React, API
