Repository bomlang/FESP01-Final-Project, pull requests merged in 2023-12, with the labels that each got.

#54 관련된 영상, 댓글 추가로 가져오는 함수 분리
  src/components/VideoComponets.tsx
  src/pages/VideoDetail.tsx
  src/pages/VideoMain.tsx
Labels: Refactor

#55 [Modify] 인터페이스에 Item타입을 추가후, 코드의 any타입을 제거하여 확실하게 명시
  .github/workflows/ gh-pages.yml
  package-lock.json
  package.json
  src/components/VideoComponets.tsx
  src/components/VideoDetailItem.tsx
  src/interface.ts
  src/layout/Header.tsx
  src/pages/VideoDetail.tsx
  src/pages/VideoMain.tsx
Labels: Docs, Fix, Deploy

#56 [Deploy] v1.0.0 메인으로 merge후 배포시도.
  .eslintrc.js
  .github/workflows/ gh-pages.yml
  .gitignore
  .prettierrc
  craco.config.js
  package-lock.json
  package.json
  public/goBack.svg
  public/index.html
  public/smile.jpeg
  public/smile.png
  public/youtubeLogo.svg
  src/App.test.tsx
  src/App.tsx
  src/api/commentApi.ts
  src/api/formatDateDifference.ts
  src/api/getRelatedVideo.ts
  src/api/getVideoAPI.ts
  src/api/getVideoData.ts
  src/components/AddComment.tsx
  src/components/BackButton.tsx
  src/components/Button.tsx
  src/components/Comment.tsx
  src/components/RelatedVideo.tsx
  src/components/SearchBar.tsx
  src/components/Spinner.tsx
  src/components/VideoComponets.tsx
  src/components/VideoDetailItem.tsx
  src/components/YoutubeVideo.tsx
  src/data.d.ts
  src/hooks/SearchVideo.ts
  src/index.css
  src/index.tsx
  src/interface.ts
  src/layout/Header.tsx
  src/layout/RootLayout/RootLayout.tsx
  src/layout/header.tsx
  src/pages/NotFound.tsx
  src/pages/VideoDetail.tsx
  src/pages/VideoMain.tsx
  src/store/channelThumbnailAtom.ts
  src/store/commentAtom.ts
  src/store/searchBarValueAtom.ts
  src/store/videoAtom.ts
  src/store/videoHoveringAtom.ts
  src/tailwind.css
  tailwind.config.js
  tsconfig.extend.json
  tsconfig.json
Labels: Deploy

#58 댓글 추가, 수정 후 리렌더링 되도록 함
  package-lock.json
  package.json
  src/components/AddComment.tsx
  src/components/Comment.tsx
  src/interface.ts
  src/layout/Header.tsx
  src/pages/VideoDetail.tsx
Labels: Feature, React

#59 [Fix] 비동기통신 코드 오류 수정
  src/components/Comment.tsx
Labels: Fix

#61 리드미 작성
  README.md
  public/detail.gif
  public/main.gif
  src/components/Comment.tsx
Labels: Docs
